name: Tests Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm run test:coverage
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: jest-report
        path: jest-report/
        retention-days: 30